### PR TITLE
Issue #313: Add path on externals install and echo message for user t…

### LINKED ISSUE #313: Mantid 4.2 moved the python modules
**Description of the error**
All tests are failing due to Mantid modules fail to be found as they have been moved in the latest release

**Describe the expected result**
Modules should be found

**Suggested fix**
add `PYTHONPATH=$PYTHONPATH:/opt/Mantid/lib` to Travis to make it work, and print a statement to users telling them to add it to their bashrc in order to get it working

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
…o add it to a bashrc file

#### Description of Work

Fixes #313 
Adds new mantid lib location to python path after install and prints a message for the user to add it to their bashrc in order to persist it.

#### Testing Instructions

1. Verify that the message makes sense
2. Verify that tests run (They'll fail when importing mantid if it doesn't work)

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

File: build/install/mantid.sh [hunk 1]
```diff
@@ -19,3 +19,7 @@ sudo apt-add-repository ppa:mantid/mantid -y
 
 sudo apt-get update
 sudo apt-get install mantid -y
+
+PYTHONPATH=$PYTHONPATH:/opt/Mantid/lib
+echo "Mantid is now setup for this session."
+echo "To enable mantid in future sessions we recommend adding 'PYTHONPATH=$PYTHONPATH:/opt/Mantid/lib' to your .bashrc file"
```
Comment (wathen) [inline build/install/mantid.sh]:
```suggestion
echo "To enable mantid in future sessions we recommend adding 'export PYTHONPATH=$PYTHONPATH:/opt/Mantid/lib' to your .bashrc file"
```
